// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: proto/signal.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          string                 `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Sdp           string                 `protobuf:"bytes,3,opt,name=sdp,proto3" json:"sdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePeerRequest) Reset() {
	*x = CreatePeerRequest{}
	mi := &file_proto_signal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePeerRequest) ProtoMessage() {}

func (x *CreatePeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePeerRequest.ProtoReflect.Descriptor instead.
func (*CreatePeerRequest) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePeerRequest) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *CreatePeerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePeerRequest) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

type CreatePeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peerId,proto3" json:"peerId,omitempty"`
	AnswerSdp     string                 `protobuf:"bytes,2,opt,name=answerSdp,proto3" json:"answerSdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePeerResponse) Reset() {
	*x = CreatePeerResponse{}
	mi := &file_proto_signal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePeerResponse) ProtoMessage() {}

func (x *CreatePeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePeerResponse.ProtoReflect.Descriptor instead.
func (*CreatePeerResponse) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePeerResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *CreatePeerResponse) GetAnswerSdp() string {
	if x != nil {
		return x.AnswerSdp
	}
	return ""
}

type AddCandidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peerId,proto3" json:"peerId,omitempty"`
	Candidate     string                 `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCandidateRequest) Reset() {
	*x = AddCandidateRequest{}
	mi := &file_proto_signal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCandidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCandidateRequest) ProtoMessage() {}

func (x *AddCandidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCandidateRequest.ProtoReflect.Descriptor instead.
func (*AddCandidateRequest) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{2}
}

func (x *AddCandidateRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *AddCandidateRequest) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_signal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_proto_signal_proto protoreflect.FileDescriptor

const file_proto_signal_proto_rawDesc = "" +
	"\n" +
	"\x12proto/signal.proto\x12\x05proto\"Q\n" +
	"\x11CreatePeerRequest\x12\x12\n" +
	"\x04room\x18\x01 \x01(\tR\x04room\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x10\n" +
	"\x03sdp\x18\x03 \x01(\tR\x03sdp\"J\n" +
	"\x12CreatePeerResponse\x12\x16\n" +
	"\x06peerId\x18\x01 \x01(\tR\x06peerId\x12\x1c\n" +
	"\tanswerSdp\x18\x02 \x01(\tR\tanswerSdp\"K\n" +
	"\x13AddCandidateRequest\x12\x16\n" +
	"\x06peerId\x18\x01 \x01(\tR\x06peerId\x12\x1c\n" +
	"\tcandidate\x18\x02 \x01(\tR\tcandidate\"\x15\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xbb\x01\n" +
	"\x06IonSFU\x12A\n" +
	"\n" +
	"CreatePeer\x12\x18.proto.CreatePeerRequest\x1a\x19.proto.CreatePeerResponse\x129\n" +
	"\x0fAddICECandidate\x12\x1a.proto.AddCandidateRequest\x1a\n" +
	".proto.Ack\x123\n" +
	"\tClosePeer\x12\x1a.proto.AddCandidateRequest\x1a\n" +
	".proto.AckB(Z&tangthetoan.com/signaling-server/protob\x06proto3"

var (
	file_proto_signal_proto_rawDescOnce sync.Once
	file_proto_signal_proto_rawDescData []byte
)

func file_proto_signal_proto_rawDescGZIP() []byte {
	file_proto_signal_proto_rawDescOnce.Do(func() {
		file_proto_signal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_signal_proto_rawDesc), len(file_proto_signal_proto_rawDesc)))
	})
	return file_proto_signal_proto_rawDescData
}

var file_proto_signal_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_signal_proto_goTypes = []any{
	(*CreatePeerRequest)(nil),   // 0: proto.CreatePeerRequest
	(*CreatePeerResponse)(nil),  // 1: proto.CreatePeerResponse
	(*AddCandidateRequest)(nil), // 2: proto.AddCandidateRequest
	(*Ack)(nil),                 // 3: proto.Ack
}
var file_proto_signal_proto_depIdxs = []int32{
	0, // 0: proto.IonSFU.CreatePeer:input_type -> proto.CreatePeerRequest
	2, // 1: proto.IonSFU.AddICECandidate:input_type -> proto.AddCandidateRequest
	2, // 2: proto.IonSFU.ClosePeer:input_type -> proto.AddCandidateRequest
	1, // 3: proto.IonSFU.CreatePeer:output_type -> proto.CreatePeerResponse
	3, // 4: proto.IonSFU.AddICECandidate:output_type -> proto.Ack
	3, // 5: proto.IonSFU.ClosePeer:output_type -> proto.Ack
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_signal_proto_init() }
func file_proto_signal_proto_init() {
	if File_proto_signal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_signal_proto_rawDesc), len(file_proto_signal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_signal_proto_goTypes,
		DependencyIndexes: file_proto_signal_proto_depIdxs,
		MessageInfos:      file_proto_signal_proto_msgTypes,
	}.Build()
	File_proto_signal_proto = out.File
	file_proto_signal_proto_goTypes = nil
	file_proto_signal_proto_depIdxs = nil
}
