// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.31.1
// source: proto/ion_signal.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IonSFUClient is the client API for IonSFU service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IonSFUClient interface {
	CreatePeer(ctx context.Context, in *CreatePeerRequest, opts ...grpc.CallOption) (*CreatePeerResponse, error)
	AddICECandidate(ctx context.Context, in *AddCandidateRequest, opts ...grpc.CallOption) (*Ack, error)
	ClosePeer(ctx context.Context, in *ClosePeerRequest, opts ...grpc.CallOption) (*Ack, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type ionSFUClient struct {
	cc grpc.ClientConnInterface
}

func NewIonSFUClient(cc grpc.ClientConnInterface) IonSFUClient {
	return &ionSFUClient{cc}
}

func (c *ionSFUClient) CreatePeer(ctx context.Context, in *CreatePeerRequest, opts ...grpc.CallOption) (*CreatePeerResponse, error) {
	out := new(CreatePeerResponse)
	err := c.cc.Invoke(ctx, "/proto.IonSFU/CreatePeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ionSFUClient) AddICECandidate(ctx context.Context, in *AddCandidateRequest, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/proto.IonSFU/AddICECandidate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ionSFUClient) ClosePeer(ctx context.Context, in *ClosePeerRequest, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/proto.IonSFU/ClosePeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ionSFUClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/proto.IonSFU/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IonSFUServer is the server API for IonSFU service.
// All implementations must embed UnimplementedIonSFUServer
// for forward compatibility
type IonSFUServer interface {
	CreatePeer(context.Context, *CreatePeerRequest) (*CreatePeerResponse, error)
	AddICECandidate(context.Context, *AddCandidateRequest) (*Ack, error)
	ClosePeer(context.Context, *ClosePeerRequest) (*Ack, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedIonSFUServer()
}

// UnimplementedIonSFUServer must be embedded to have forward compatible implementations.
type UnimplementedIonSFUServer struct {
}

func (UnimplementedIonSFUServer) CreatePeer(context.Context, *CreatePeerRequest) (*CreatePeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePeer not implemented")
}
func (UnimplementedIonSFUServer) AddICECandidate(context.Context, *AddCandidateRequest) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddICECandidate not implemented")
}
func (UnimplementedIonSFUServer) ClosePeer(context.Context, *ClosePeerRequest) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClosePeer not implemented")
}
func (UnimplementedIonSFUServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedIonSFUServer) mustEmbedUnimplementedIonSFUServer() {}

// UnsafeIonSFUServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IonSFUServer will
// result in compilation errors.
type UnsafeIonSFUServer interface {
	mustEmbedUnimplementedIonSFUServer()
}

func RegisterIonSFUServer(s grpc.ServiceRegistrar, srv IonSFUServer) {
	s.RegisterService(&IonSFU_ServiceDesc, srv)
}

func _IonSFU_CreatePeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IonSFUServer).CreatePeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IonSFU/CreatePeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IonSFUServer).CreatePeer(ctx, req.(*CreatePeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IonSFU_AddICECandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCandidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IonSFUServer).AddICECandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IonSFU/AddICECandidate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IonSFUServer).AddICECandidate(ctx, req.(*AddCandidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IonSFU_ClosePeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClosePeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IonSFUServer).ClosePeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IonSFU/ClosePeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IonSFUServer).ClosePeer(ctx, req.(*ClosePeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IonSFU_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IonSFUServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IonSFU/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IonSFUServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IonSFU_ServiceDesc is the grpc.ServiceDesc for IonSFU service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IonSFU_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.IonSFU",
	HandlerType: (*IonSFUServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePeer",
			Handler:    _IonSFU_CreatePeer_Handler,
		},
		{
			MethodName: "AddICECandidate",
			Handler:    _IonSFU_AddICECandidate_Handler,
		},
		{
			MethodName: "ClosePeer",
			Handler:    _IonSFU_ClosePeer_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _IonSFU_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ion_signal.proto",
}
